services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
    volumes:
      - ./cassandra.cql:/tmp/cassandra.cql